### ISSUE TITLE
Excuse me, do you know how to linearize the system when using MPC?

### ISSUE THREAD

**Issue by joker-csee** [martiabr/flying-inverted-pendulum#1]

**Comment by martiabr** [comment]
If you have a look at the paper this implementation was based on with the same name, you can find the equations of motion. At least for the constant position case, it should be fairly straightforward to linearize it.

**Comment by joker-csee** [comment]
In the paper, it seems the model is simplified by kinematics, and the link it provides failed when I try to find more details about it. Do you know where to get more information, and how can this problem be solved in a more general trajectory?

**Comment by martiabr** [comment]
If you want the FIP to follow a general trajectory I would look into nonlinear MPC and how to use NMPC for target tracking / path following. I don't know enough about this stuff yet to say anything more specific than that, but googling that might help...

**Comment by joker-csee** [comment]
Well, thanks for your help. I'm trying to figure it out.
